---
- hosts: webservers
  become: yes
  tasks:
  - name: instal git
    apt:
      name: git
      state: present
  
  - name: install tree
    apt:
      nameee: tree
      state: present
    ignore_errors: yes

  - name: install wget
    apt: 
      name: wget
      state: present