---
- hosts: webservers
  become: yes
  tasks:
  - name: instal git
    apt:
      name: git
      state: present
  
  - name: install tree
    apt:
     nameeee: tree
     state: present
     
  - name: install wget
    apt: 
      name: wget
      state: present