---
- hosts: webservers
  become: yes
  tasks: 
  - name: i want to install multi packages on ubuntu16
    apt:
        name: "{{ item }}"
        loop: 
          - git
          - tree
          - wget
        when: ansible_os_family =="Debian"
  - name: i want to install multi packages on redhat
    yum:
        name: "{{ item }}"
        loop: 
          - git
          - tree
          - wget
        when: ansible_os_family =="RedHat"

    
